/**
 * Simeon Smith
 * 6/16/2015
 * Analyze Duel #3
 */

/*******VARIABLES*******/
/*var player1 = "Bug Face",           //Player 1's Name
    player2 = "Scar Fist",          //Player 2's Name
    p1Health = 100,                 //Player 1's Health
    p2Health = 100,                 //Player 2's Health
    p1MaxDmg = 20,                  //Player 1's Max Damage
    p2MaxDmg = p1MaxDmg,            //Player 2's Max Damage = Player 1's
    round = 1,                      //ROUND NUMBER SETUP
    gameOver = false;               //Game Over set to false*/

var players = [
        {             //Player 1 Object
            name:'Bug Face',
            health: 100,
            damage: 20,
            healthDis: document.querySelector('#kabal p')
        },
        {             //Player 2 Object
            name:'Scar Fist',
            health: 100,
            damage: 20,
            healthDis: document.querySelector('#kratos p')
        }
    ],
    round = 1,                          //ROUND NUMBER SETUP
    gameOver = false,                   //Game Over set to false
    fightBtn = document.querySelector('#fight_btn a.buttonblue');

/*******FUNCTIONS*******/
/*Fight Function*/
function fight(max){                   //Fight calculations function
    var min,
        dmg;

    min = max * .5;
    dmg = Math.floor(Math.random() * (max - min)) + min;    //Calculate a random number with the max and min from the arguments
    return dmg;                                                 //Return the damage value.
}

/*Winner Check Function*/
function winnerCheck(p1Health, p2Health, round){       //Check winner function
    if(p1Health <=0 && p2Health <=0){                       //If both players health is 0 or below execute
        return "You Both Die!";                                 //Return "You Both Die!"
    }else if(p1Health <=0){                                 //If Player 1's health is 0 or below execute
        return players[1].name + " Wins!";                               //Return "P2Name Wins!"
    }else if(p2Health <=0) {                                //If Player 2's health is 0 or below execute
        return players[0].name + " Wins!";                               //Return "P1Name Wins!"
    }else if(round === 10){                                   //If round is greater than 10 execute
        if (p1Health > p2Health){                               //If Player 1's health is greater than Player 2's execute.
            return players[0].name + " Wins!";                               //Return "P1Name Wins!"
        }else if (p2Health > p1Health){                         //If Player 2's health is greater than Player 1's execute
            return players[1].name + " Wins!";                               //Return "P2Name Wins!"
        }else{                                                  //Else execute
            return "You Tied!";                                     //Return "You Tied!"
        }
    }else{                                                  //Else execute
        return false;                                       //Return false
    }
}

/*INITIAL SETUP BEFORE LOOKING AT EXAMPLE*/
function whileLoop() {
    //alert(players[0].name + ' : ' + players[0].health + ' *START* ' + players[1].name + ' : ' + players[1].health);   //Starting Alert
    while (!gameOver) {          //While gameOver is false execute

        players[0].health -= fight(players[1][2]);     //Subtract the number generated by the fight function from Player 1's health based on the Player 2's max damage
        players[1].health -= fight(players[0][2]);     //Subtract the number generated by the fight function from Player 2's health based on the Player 1's max damage

        gameOver = winnerCheck(players[0].health, players[1].health, round);  //Set the value of the winnerCheck function to gameOver based on the arguments

        if (gameOver) {           //If gameOver is true execute
            //alert(gameOver);        //Alert user with the results of the fight.
        } else {                  //Else execute.
            //alert(players[0].name + ' : ' + players[0].health + ' *ROUND ' + round + ' IS OVER* ' + players[1].name + ' : ' + players[1].health);    //Alert user with the results of the round.
            round++;       //Add 1 to the round.
        }

    }
}

/*Using a for loop as specified*/

fightBtn.addEventListener('click', function(){
    var roundDis = document.getElementById('round');
    var scoresDis = document.getElementById('scores');

    players[0].health -= fight(players[1].damage); //Subtract the number generated by the fight function from Player 1's health based on the Player 2's max damage
    players[1].health -= fight(players[0].damage); //Subtract the number generated by the fight function from Player 2's health based on the Player 1's max damage

    gameOver = winnerCheck(players[0].health, players[1].health, round);  //Set the value of the winnerCheck function to gameOver based on the arguments

    if (!gameOver) {      //If game over is false execute.
        for (i = 0, j = players.length; i < j; i++) {           //For each item in players array execute the following.
            players[i].healthDis.innerHTML = players[i].health;     //Set the innerHTML of the score p element to the players health.
        }

        roundDis.innerHTML = 'Round ' + round + ' Complete';

        round++;                //Add 1 to round.
    } else {              //Else execute

        roundDis.innerHTML = 'Round ' + round + ' Complete';
        scoresDis.innerHTML = '<p>'+ gameOver + '</p>' + '<div class="clear"></div>';
    }
});

/*******MAIN CODE*******/

/***SETUP HEALTH*****/
for (i = 0, j = players.length; i < j; i++) {           //For each item in players array execute the following.
    players[i].healthDis.innerHTML = players[i].health;     //Set the innerHTML of the score p element to the players health.
}

//forLoop();  //Run the forLoop function.